// <auto-generated />
using System;
using IntimacyAI.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntimacyAI.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250914173330_ExpandDomain")]
    partial class ExpandDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("IntimacyAI.Server.Models.AnalysisHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnalysisType")
                        .HasColumnType("TEXT")
                        .HasColumnName("analysis_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("MetadataJsonEncrypted")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("ScoresJsonEncrypted")
                        .HasColumnType("TEXT")
                        .HasColumnName("scores_json");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.ToTable("analysis_history", (string)null);
                });

            modelBuilder.Entity("IntimacyAI.Server.Models.CoachingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FeedbackJsonEncrypted")
                        .HasColumnType("TEXT")
                        .HasColumnName("feedback_json");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("SuggestionsJsonEncrypted")
                        .HasColumnType("TEXT")
                        .HasColumnName("suggestions_json");

                    b.HasKey("Id");

                    b.ToTable("coaching_sessions", (string)null);
                });

            modelBuilder.Entity("IntimacyAI.Server.Models.ModelPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccuracyMetricsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("accuracy_metrics");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ModelVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_version");

                    b.Property<string>("PerformanceMetricsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("performance_metrics");

                    b.HasKey("Id");

                    b.ToTable("model_performance", (string)null);
                });

            modelBuilder.Entity("IntimacyAI.Server.Models.UsageAnalytics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnonymousUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("anonymous_user_id");

                    b.Property<string>("AppVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("app_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FeatureUsed")
                        .HasColumnType("TEXT")
                        .HasColumnName("feature_used");

                    b.Property<string>("Platform")
                        .HasColumnType("TEXT")
                        .HasColumnName("platform");

                    b.Property<int?>("UsageDurationSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usage_duration");

                    b.HasKey("Id");

                    b.ToTable("usage_analytics", (string)null);
                });

            modelBuilder.Entity("IntimacyAI.Server.Models.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PreferencesJsonEncrypted")
                        .HasColumnType("TEXT")
                        .HasColumnName("preferences_json");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_preferences", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
