// <auto-generated />
using System;
using IntimacyAI.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntimacyAI.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("IntimacyAI.Server.Models.ModelPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccuracyMetricsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("accuracy_metrics");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ModelVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_version");

                    b.Property<string>("PerformanceMetricsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("performance_metrics");

                    b.HasKey("Id");

                    b.ToTable("model_performance", (string)null);
                });

            modelBuilder.Entity("IntimacyAI.Server.Models.UsageAnalytics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnonymousUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("anonymous_user_id");

                    b.Property<string>("AppVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("app_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FeatureUsed")
                        .HasColumnType("TEXT")
                        .HasColumnName("feature_used");

                    b.Property<string>("Platform")
                        .HasColumnType("TEXT")
                        .HasColumnName("platform");

                    b.Property<int?>("UsageDurationSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usage_duration");

                    b.HasKey("Id");

                    b.ToTable("usage_analytics", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
