name: Android Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'intimacy-ai/platform/android/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v2
      - name: Build release (assembleRelease)
        working-directory: intimacy-ai/platform/android
        run: |
          ./gradlew --no-daemon assembleRelease
      - name: Copy arm64 APK
        working-directory: intimacy-ai/platform/android
        run: |
          mkdir -p dist
          ARM64=$(ls app/build/outputs/apk/release/*arm64*-release*.apk | head -n1 || true)
          if [ -n "$ARM64" ]; then cp "$ARM64" dist/IntimacyAI-S22-arm64-v8a-release.apk; fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apks
          path: |
            intimacy-ai/platform/android/app/build/outputs/apk/release/*.apk
            intimacy-ai/platform/android/dist/*.apk
