name: Build and Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore intimacy-ai/IntimacyAI.sln

      - name: Build
        run: dotnet build --no-restore -c Release intimacy-ai/IntimacyAI.sln

      - name: Test
        run: dotnet test --no-build -c Release --verbosity normal intimacy-ai/tests/IntimacyAI.Tests/IntimacyAI.Tests.csproj
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore intimacy-ai/IntimacyAI.sln
      - name: Build
        run: dotnet build intimacy-ai/IntimacyAI.sln -c Release --no-restore
      - name: Test
        run: dotnet test intimacy-ai/IntimacyAI.sln -c Release --no-build